### ISSUE TITLE
Render <details>

### ISSUE THREAD

**Issue by larseggan** [MyNihongo/MudBlazor.Markdown#114]
a `<details>` tag is not rendered correctly.
Example where the "Release 1.0.1" is not rendered:

<details>
  <summary markdown="span">Release 1.0.1</summary>
**New**
-  Error fixes.
</details>

**Comment by larseggan** [comment]
Details tag is not rendered correctly.

**Comment by MihailsKuzmins** [comment]
If the `<details>` block is not nested within any other html tag it will be rendered as `MudExpansionPanel` as shown below. You can nest them as well
![details-dark](https://user-images.githubusercontent.com/47413092/187035261-3c322c2f-e245-4050-93f1-27312c88aa4e.jpg)

Otherwise the default browser `<details>` implementation takes place
![image](https://user-images.githubusercontent.com/47413092/187035342-088ab0de-db17-4227-be04-cd268c0a3ea9.png)
