### ISSUE TITLE
Line breaks not preserved following code blocks

### ISSUE THREAD

**Issue by jstafford5380** [MyNihongo/MudBlazor.Markdown#129]
Line breaks in the markdown files appear to be removed following code blocks

Example markdown
![image](https://user-images.githubusercontent.com/47302800/199313649-a9139783-a0b3-4802-9b30-eb24f34a1ae9.png)

Rendered result
![image](https://user-images.githubusercontent.com/47302800/199313720-ebc7748d-cfb5-4fde-ab5a-bda250bd47fb.png)

**Comment by MihailsKuzmins** [comment]
It is not the `Line break` issue. The behavour which removes redundant empty lines is the correct behaviour for the markdown specification.

It is the same in the GitHub markdown. The result is the same whether there is an empty line in the markdown file or not.
![image](https://user-images.githubusercontent.com/47413092/199377477-e9057bf2-0c00-4880-ac70-c6b1400d6f53.png)

However, it is a good idea to add some spacing after the code block so that the next block is not so close.

**Comment by MihailsKuzmins** [comment]
@jstafford5380 could you please provide the sample where the space is not present? Maybe you use a different theme or something. I cannot reproduce this with my default settings

This is my markdown
![image](https://user-images.githubusercontent.com/47413092/199729848-1c19cf97-cba6-4ffa-a6c1-5ba9e10f0d07.png)

And this is how it's rendered
![image](https://user-images.githubusercontent.com/47413092/199729995-92e93e51-df05-4600-b1f1-4732434b36d7.png)  
![image](https://user-images.githubusercontent.com/47413092/199730316-c6550562-ce1e-46de-8837-6f17477b5606.png)

So as you can see the spacing is fine. Maybe you override it somewhere in your css files?
