### ISSUE TITLE
Code Markdown

### ISSUE THREAD

**Issue by Killers0992** [MyNihongo/MudBlazor.Markdown#36]
Its possible to get support for code markdown? like
```yml
config: test
config2: test2
```
etc

**Comment by my-nihongo** [comment]
@Killers0992 so far this is not implemented in the library
I have already thought about this problem and I had an idea of implementing it with [highlight.js](https://www.npmjs.com/package/highlight.js?activeTab=readme), but have not started doing it

To be honest, I am not really sure when I can try to start doing it (probably I will try to do it a bit later this week)

**Comment by MihailsKuzmins** [comment]
This should be done by #38.
Please refer to the [upgrade guide](https://github.com/MyNihongo/MudBlazor.Markdown/wiki/Update-guide#update-to-005) because there are some changes

For toggling dark/light modes please refer to this code sample
https://github.com/MyNihongo/MudBlazor.Markdown/blob/33a06db5b6f5c024134fba7ed7dd2ea306f03b97/samples/MudBlazor.Markdown.Core/Services/ThemeService.cs#L48-L54

For a basic usage please refer to
https://github.com/MyNihongo/MudBlazor.Markdown/blob/33a06db5b6f5c024134fba7ed7dd2ea306f03b97/samples/Server/Pages/Index.razor#L5-L8

I hope it will work 😃
